[package]
name = "astrea"
version = "0.1.0"
authors = ["Rafi Baum <rafi@ukbaums.com>"]
edition = "2018"

[dependencies]
hyper = "0.13.0-alpha.4"
tokio = "0.2.0-alpha.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"